Ajout de discord-logs pour créer des channel vocaux sur demande (colearning channels)
IESN-IG/DataDrop pull request #21
Opened 2020-09-29 12:37 UTC by Whuski

J'ai donc utilisé le paquets que Thibault m'a recommandé. J'ai créer une nouvelle collection dans le client qui gèrent les channels créer dynamiquement 
Lorsque que l'utilisateur rejoint un channel vocal spécifique (Id dans le config -> colearningChannelid), ça clone ce channel et y déplace l'utilisateur. 
Une fois qu'un utilisateur quitte le channel ça regarde si celui-ci est vide et si c'est le cas ça le supprime.

2020-09-29 15:59 UTC, HunteRoi commented
Bien que le co-learning soit une cible principale pour cette fonctionnalité, je pense qu'il est préférable de rester général. 
Ainsi:

- Pour chaque bloc, un canal vocal unique existe. 
- Pour chaque personne qui rentre dedans, un nouveau canal vocal est créé dans ce même bloc (la même catégorie donc).
- La personne ayant déclenché la création du canal devient propriétaire. Elle obtient des droits de modification sur ce canal uniquement (en outre le nom du canal). 
- Une fois un canal créé dynamiquement vide, il est supprimé.

Cela répondrait ainsi à plusieurs cas de figure : le co-learning, les cours en ligne (salle de classe), la possibilité pour les étudiants de créer des canaux "de groupes d'étude", ...

2020-09-29 16:14 UTC, HunteRoi requested changes

2020-09-29 16:14 UTC, HunteRoi commented on datadrop.js
>  client.commands = new Collection();
Ajoute un blanc en ligne 13 et retire celui de la ligne 15. Tu peux également appeler la méthode `discordLogs` de manière plus explicite comme `addDiscordLogsFramework` par exemple.

2020-09-29 16:14 UTC, HunteRoi commented on config.js
> +    // Before pushing these changes we need to create a co-learning voice channel
Pas besoin de commentaire. C'est une information qui doit se retrouver dans la description de la pull request.

Le nom de la clé devrait perdre son suffixe "colearning" comme exprimé dans mon message sur l'overview de la PR (#21). J'imagine que blocUnChannelid, blocDeuxChannelid et blocTroisChannelid devraient faire l'affaire.

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +    if (channel.id === config.colearningChannelid) {
Ceci ne marche évidemment que dans le cas d'un seul canal de colearning qui en génère d'autres. Il serait peut-être judiciable d'utiliser un tableau de channelids ou même d'employer un switch si nécessaire.

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +            log.warn("There was an error creating a new colearning channel");
Log l'exception qui est survenue :wink:

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +        } catch (reasons) {
En règle générale, un catch ne récupère qu'une exception en paramètre. Tu peux donc sans faute renommer la variable `reasons` en `e` ou `exception`.

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +            newChannel.setName("Co-learning");
Il serait intéressant d'assigner à l'utilisateur déclencheur de cet événement des permissions sur le canal nouvellement créé. Qu'en penses-tu?

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +            log.warn("There was an error creating a new colearning channel");
Et aussi, c'est une erreur donc utilise le log approprié => `log.error`

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelLeave.js
> +        if (channel.members.size <= 0) {
As-tu déjà rencontré un canal dont la taille est négative? Tu n'es pas obligé de vérifier ce use case qui n'arrivera jamais. Une simple condition `=== 0` est suffisante :D

2020-09-29 16:14 UTC, HunteRoi commented on events/voiceChannelLeave.js
> +        if (channel.members.size <= 0) {
Tu peux merger les 2 ifs en un seul.

2020-10-03 13:13 UTC, Whuski commented
- J'ai imaginé la solution suivante pour la création de channel dynamique : un tableau dans le fichier config qui permet de facilement ajouter un ID qui rendrait un channel vocal "dynamique", le comportement est toujours le même, on clone le channel. Seul soucis c'est qu'on risque de s'y perdre dans le fichiers config. Plusieurs solution pour ça : repenser la structure, commenter le fichier config.
- J'ai ajouté la permission "MANAGE_CHANNEL" au créateur du channel. Ajouter MANAGE_ROLES lui permet d'avoir beaucoup plus de contrôle sur le channel mais ça crée aussi des effets bizarres (discord lui dit qu'il peut cloner et créer des channels mais ça crash quand il clique sur OK)
- J'ai nettoyé le code voiceStateUpdate (supprimer quoi x) )

Voilà dis moi ce que t'en penses !

2020-10-04 18:25 UTC, HunteRoi requested changes

2020-10-04 18:25 UTC, HunteRoi commented on events/voiceChannelJoin.js
> +            //Should the new channel have a new name? What should it be?
Tu peux nommer le canal en utilisant le nom de la personne qui a activé la création de ce dernier

2020-10-04 18:36 UTC, HunteRoi commented on config.js
> +    ],
Tu peux utiliser ceci:
```js
dynamicVoiceChannelids: [
	619190601383936000, // co-learning common-profs-étu
	762381363532922892, // salon public IG1
	762381732615684157, // salon public IG2,
	762381873720066098, // salon public IG3,
	762382057157558352 // vocal entertainment
],
```

Autre note: il n'y a pas de s après "channel" et avant "id" : `dynamicVoiceChannelsids` => `dynamicVoiceChannelids`

2020-10-06 17:41 UTC, HunteRoi requested changes

2020-10-06 17:41 UTC, HunteRoi commented on events/voiceChannelJoin.js
>              newChannel = await channel.clone();
````js
const newOptions = {
  name: `Salle de ${member.nickname}`,
  parent: channel.parentID,
  permissionOverwrites: [{
    id: member.id, 
    allow: ["MANAGE_CHANNELS"],
    type: "member"
  }]
};
newChannel = await channel.clone(newOptions);
````

2020-10-06 17:42 UTC, HunteRoi commented on events/voiceChannelJoin.js
>              newChannel = await channel.clone();
On y est presque! @Whuski !

2020-10-06 17:46 UTC, HunteRoi commented
J'ai modifié ta PR afin que tu pousses tes changements sur une branche `features/dynamic-vchannels` afin que je teste les changements avec la version bêta du bot (histoire de pas pousser en prod inutilement).
Chose que je n'avais pas remarqué avant : ne base pas ta PR sur la branche master mais plutôt sur la branche develop! Tu peux en apprendre plus sur la manière utilisée pour développer ce projet en faisant des recherches sur le "gitflow workflow" :wink:

2020-10-06 17:50 UTC, HunteRoi commented
Dernière chose puis promis, j'arrête de t'embêter pour aujourd'hui! Tu as bien supprimé l'event **voiceStateUpdate** mais il reste du code à certains endroits dans le bot concernant les salles de classe! Vérifie la PR #9 et le commit de merge sur master pour plus d'infos : https://github.com/IESN-IG/DataDrop/commit/7c129d0d18eea7c7ddcdd24e41a5474d3534c7e8

Bonne soirée à toi et merci pour ton travail très apprécié! Tu me sauves énormément de temps 😍

2020-10-07 10:49 UTC, Whuski commented
Heyoo j'ai fait les changements demandés  ! Merci pour les infos sur le git workflow ce fut une bonne lecture 😄 

Globalement c'est assez cool pour moi parce que j'apprends à utiliser git (et j'aime bien chipoter avec les bots discord)

2020-10-07 21:31 UTC, HunteRoi approved these changes

2020-10-07 21:32 UTC, merged