Feature: use package.json version instead of the one from env file
IESN-IG/DataDrop pull request #38
Opened 2022-09-12 22:50 UTC by DrakeXorn

Just doing this to prevent having to change it every time the bot has an upgrade :^)

2022-09-14 13:16 UTC, HunteRoi requested changes

2022-09-14 13:16 UTC, HunteRoi commented on .github/workflows/deployment.yml
> +            NODE_ENV=production pm2 restart ${{secrets.APP_NAME}} --update-env
tu devrais pas rajouter un `&&` entre l'assignation de la variable d'environnement et l'appel à pm2 ?

2022-09-14 13:16 UTC, HunteRoi commented on ecosystem.config.js
> +    log_date_format: "DD-MM-YYYY HH:mm:ss",
Les millisecondes pourraient être intéressantes aussi ;)

2022-09-14 13:16 UTC, HunteRoi commented on src/config.ts
> +import { version } from "package";
```suggestion
import { version } from '@package';
```

2022-09-14 13:16 UTC, HunteRoi commented on tsconfig.json
> +      "package": ["package.json"]
```suggestion
      "@package": ["package.json"]
```

2022-09-14 14:29 UTC, DrakeXorn commented on .github/workflows/deployment.yml
> +            NODE_ENV=production pm2 restart ${{secrets.APP_NAME}} --update-env
Ce n'est pas ce que j'ai vu dans la documentation de pm2 en tout cas...
https://pm2.io/docs/runtime/best-practices/environment-variables/#set-environment

2022-09-15 10:11 UTC, HunteRoi commented on src/config.ts
> +const formattedEnvironment = `${environment.charAt(0).toUpperCase()}${environment.slice(1, 4).toLowerCase()}`;
Tu te fais vachement chier pour un title case :issou:

2022-09-15 10:11 UTC, HunteRoi approved these changes

2022-09-15 10:11 UTC, merged